server:
  port: 8080

spring:
  application:
    name: honey-storyboard

  datasource:
    hikari:
      maximum-pool-size: 50
      jdbc-url: jdbc:mysql://storyboard-mysql.c0g21czpi04j.ap-northeast-2.rds.amazonaws.com:3306/storyboard
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: jeongyong95
      password: vmfhgod11

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    user:
      name: honey
      password: 980119