project:
  studymaker-backend

server:
    port: 10001

spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://studymaker-postgre.c0g21czpi04j.ap-northeast-2.rds.amazonaws.com:5432/studymaker_dev
      username: studymaker
      password: tmxjelapdlzj2021!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: studymaker-redis.bm6rno.0001.apn2.cache.amazonaws.com
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  secret: studymaker_is_good_web_application_for_developer
  issuer: studymaker
  tokenValidityTimeLimit: 600000